version: '3.8'

services:
  qianmusic:
    image: yyy887/qianmusic:latest
    container_name: qianmusic
    restart: unless-stopped
    ports:
      - "7749:7749"
    environment:
      - NODE_ENV=production
      - PORT=7749
      - CORS_ALLOW_ORIGIN=*
      - ENABLE_PROXY=false
      - ENABLE_GENERAL_UNBLOCK=true
      - ENABLE_FLAC=true
      - SELECT_MAX_BR=false
      - FOLLOW_SOURCE_ORDER=true
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:7749"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
